### ISSUE TITLE
Remove client side bcrypt.

### ISSUE THREAD

**Issue by phouse512** [mxstbr/login-flow#37] opened 2017-10-27 20:02 UTC
https://github.com/mxstbr/login-flow/blob/44b34885d0bbfac18d57bd7879f886f022817774/js/actions/AppActions.js#L51

I would modify this example to *not* hash the password on the client side (unless it is also being done on the server).  Briefly, if you are using a secured communication protocol (SSL, for example), then there is no need to hash this here. 

If anything, it's better to leave it on the server side - see [this post](https://security.stackexchange.com/questions/8596/https-security-should-password-be-hashed-server-side-or-client-side) for more info.

**Comment by mxstbr** [comment] 2017-10-27 20:51
Duplicate of #31. I hash on the server too.

**Closed as completed by mxstbr** 2017-10-27 20:51 UTC
